name: Update progress bar
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  update-progress-bar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run script
        run: |
          pip install -r Progress/requirements.txt
          python Progress/progress_bar.py

      - name: Update Readme
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: "chore(readme.md): update exercise progress"
          github-token: ${{ secrets.GITHUB_TOKEN }}
